### PR TITLE
Add labels for exit this page and task list components

### PR DESCRIPTION
**Pull request by 36degrees**

### CODE REVIEW

**Comment by 36degrees** [comment]
This isn't adding a task list label because, of course, we already have one as a pattern that has the same text.

If we want to distinguish between them I think we'd need to differentiate somehow e.g. 'task list (component)'

Thoughts?

**Comment by kellylee-gds** [comment]
Yeah that sounds good to me!

**Comment by owenatgov** [comment]
I think the distinction is good for now. I wonder if we should still have the pattern at all but that's a chat for later.

**Review by owenatgov — APPROVED** [review]
After chatting to @36degrees on slack, until we've decided what we're doing with task list ie: should we keep it as a pattern, let's just get this in.

**Pull request merged**
